# Generated by Django 6.0.7 on 2026-07-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lalafo_appdrf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ky',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discriptions_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discriptions_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discriptions_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
